version: "3.2"
services:
  php:
    build: 
      context: './'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - laravel-app/:/var/www/html/
    container_name: php

